version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: garage_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: garage_db
      MYSQL_USER: garage_user
      MYSQL_PASSWORD: motdepasse
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  db_data: